### ISSUE TITLE
Lambda functions using deprecated nodejs4.3

### ISSUE THREAD

**Issue by EricSAws** [awslabs/efs-backup#13]
I have a client with this deployed in production and they are receiving warning notices that the lambda calls are using nodejs4.3 which is now deprecated. Can the scripts be updated to 8.10?

Both the backup and restore templates contain nodejs4.3 references.

**Comment by gsingh04** [comment]
Thanks for bringing this to our attention. We are looking into it.

**Comment by hcomnetworkers** [comment]
Dear all,

we also have a client using the efs-backup in production. It would be appreciated a lot if it can be fixed soon, since the official notification tells us, that "the ability to create new Lambda functions configured to use the Node.js v4.3 runtime will be disabled on July 31, 2018".

Is there any chance, that a fix will be available within the next two weeks?

**Comment by gsingh04** [comment]
we have released efs-backup v1.3, please close the issue or feel free to update here if you face any concerns
https://aws.amazon.com/answers/infrastructure-management/efs-backup/

**Comment by hcomnetworkers** [comment]
Thanks @gsingh04. We briefly tested it on staging  and it looks good so far.
