### ISSUE TITLE
Why using "cp -l" for rotating latest backup "0" to backup "1"

### ISSUE THREAD

**Issue by FalkoBasner** [awslabs/efs-backup#7]
Hi,

maybe its more a question about script efs-backup-fpsync.sh.

Before this script triggers the creation of a new backup, it is rotating all existing backups.

```
echo "create_snapshot_start:$(date -u +%FT%T)"
# copy first backup with hard links, then replace first backup with new backup
if sudo test -d /mnt/backups/$efsid/$interval.0 ; then
  echo "-- $(date -u +%FT%T) --  sudo cp -al /mnt/backups/$efsid/$interval.0 /mnt/backups/$efsid/$interval.1"
  sudo cp -al /mnt/backups/$efsid/$interval.0 /mnt/backups/$efsid/$interval.1
fi
echo "create_snapshot_stop:$(date -u +%FT%T)"
```

Why "cp -al" is used here and not just "cp -a" ? Why using hard links here?

Thx,

best 
Falko

**Comment by stevemorad** [comment]
Hard links are used to reduce the size of each backup. Without them, every backup would contain a complete, independent copy of all the data for that day, regardless of what data changed (or did not change). With hard links, each backup only needs to contain the differences from one day to the next (differential), while still being able to perform a complete, full backup from any given day. It saves space and reduces the amount of time it takes to copy from one day to the next because only iNodes need to be created rather than copying all the underlying data. Here are some links with more information:
https://en.wikipedia.org/wiki/Hard_link
http://www.mikerubel.org/computers/rsync_snapshots/

**Comment by FalkoBasner** [comment]
Thanks for the quick reply and explanation!

I have one further question to the fpsync after rotating the backups. 

Before a new backup is created daily.0 is copied ("cp -al") to daily.1. Daily.0 is now "hard" linked to daily.1. If you manually change some file in daily.0 before the backup with "fpsync" is started, this change is propagate to daily.1 as well, since it is hard linked.

So what I did not get until now is, why folder daily.1 is not changed when fpsync is creating a new backup in folder daily.0 ? Does rsync remove a hard file link and create new files when rsync have to overwrite a file?

Thanks again!

Best,
falko
